version: '3.9'

services:
  ros_jazzy_container:
    image: osrf/ros:jazzy-desktop-full
    container_name: ros_jazzy
    network_mode: "host"
    user: "root"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${PWD}/workspace-jazzy/:/ros2_jazzy_workspace  # Mounts ROS 2 workspace
      - /dev/dri:/dev/dri  # Add GPU access
      - /dev/kfd:/dev/kfd  # For AMD ROCm (if needed)
    devices:
      - /dev/dri:/dev/dri  # DRI for OpenGL rendering
    working_dir: "/ros2_jazzy_workspace"
    stdin_open: true
    tty: true
    command: >
      bash -c "echo 'source /opt/ros/jazzy/setup.bash' >> /root/.bashrc && exec bash"
    restart: unless-stopped

  ros_humble_container:
    image: osrf/ros:humble-desktop-full
    container_name: ros_humble
    network_mode: "host"
    user: "root"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Enables GUI access
      - ${PWD}/workspace-humble/:/ros2_humble_workspace  # Mounts ROS 2 workspace
      - /dev/dri:/dev/dri  # Gives access to GPU rendering (Mesa)
      - /dev/kfd:/dev/kfd  # Required for AMD ROCm if used
    devices:
      - /dev/dri:/dev/dri  # Direct Rendering Interface (DRI)
    working_dir: "/ros2_humble_workspace"
    stdin_open: true
    tty: true
    command: >
      bash -c "echo 'source /opt/ros/humble/setup.bash' >> /root/.bashrc && exec bash"
    restart: unless-stopped
