version: '3.9'

services:
  ros_container:
    image: osrf/ros:jazzy-desktop-full
    container_name: ros_jazzy
    network_mode: "host"
    user: "root"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /${PWD}/worksplace/:/ros2_workspace # mount the ros2 project's workspace folder from this repo into the container 
    working_dir: "/ROS2"
    stdin_open: true
    tty: true
